# Generated by Django 5.2.1 on 2025-06-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_police', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('acte_gestion', models.CharField(max_length=100)),
                ('numero_acte', models.CharField(max_length=100)),
                ('date_boc', models.DateField(blank=True, null=True)),
                ('statut_controle', models.CharField(default='Non contrôlé', max_length=100)),
                ('motif_reserve', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Contrat',
        ),
    ]
