# Generated by Django 5.2.1 on 2025-06-09 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0002_contrats_delete_contrat'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contrats',
            table='contracts',
        ),
    ]
