# Generated by Django 5.2.1 on 2025-06-09 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0003_alter_contrats_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrats',
            options={'managed': False},
        ),
    ]
