# Generated by Django 5.2.1 on 2025-06-09 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0004_alter_contrats_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contrats',
            table='Contrats',
        ),
    ]
